-- MySQL Script generated by MySQL Workbench
-- Wed Jan 30 20:28:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ITM_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ITM_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ITM_DB` DEFAULT CHARACTER SET utf8 ;
USE `ITM_DB` ;

-- -----------------------------------------------------
-- Table `ITM_DB`.`University`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITM_DB`.`University` ;

CREATE TABLE IF NOT EXISTS `ITM_DB`.`University` (
  `University_ID` INT NOT NULL,
  `University_Name` VARCHAR(60) NULL,
  PRIMARY KEY (`University_ID`))
ENGINE = InnoDB;

INSERT INTO `itm_db`.`university` (`University_ID`, `University_Name`) VALUES ('101', 'PSU_HY');
INSERT INTO `itm_db`.`university` (`University_ID`, `University_Name`) VALUES ('102', 'PSU_PN');
INSERT INTO `itm_db`.`university` (`University_ID`, `University_Name`) VALUES ('201', 'TSU');
INSERT INTO `itm_db`.`university` (`University_ID`, `University_Name`) VALUES ('301', 'WU');


-- -----------------------------------------------------
-- Table `ITM_DB`.`Year`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITM_DB`.`Year` ;

CREATE TABLE IF NOT EXISTS `ITM_DB`.`Year` (
  `Year` INT NOT NULL,
  PRIMARY KEY (`Year`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITM_DB`.`challenge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITM_DB`.`challenge` ;

CREATE TABLE IF NOT EXISTS `ITM_DB`.`challenge` (
  `University_ID` INT NOT NULL,
  `Year` INT NOT NULL,
  PRIMARY KEY (`University_ID`, `Year`),
  CONSTRAINT `fk_University_has_Year_University`
    FOREIGN KEY (`University_ID`)
    REFERENCES `ITM_DB`.`University` (`University_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_University_has_Year_Year1`
    FOREIGN KEY (`Year`)
    REFERENCES `ITM_DB`.`Year` (`Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITM_DB`.`Activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITM_DB`.`Activity` ;

CREATE TABLE IF NOT EXISTS `ITM_DB`.`Activity` (
  `Ativity_ID` INT NOT NULL,
  `Activity_Name` VARCHAR(45) NULL,
  `Activity_Type` VARCHAR(45) NULL,
  `Activity_date` VARCHAR(45) NULL,
  `Activitycol_Time` VARCHAR(45) NULL,
  PRIMARY KEY (`Ativity_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITM_DB`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITM_DB`.`Students` ;

CREATE TABLE IF NOT EXISTS `ITM_DB`.`Students` (
  `challenge_University_ID` INT NOT NULL,
  `challenge_Year` INT NOT NULL,
  `Ativity_Ativity_ID` INT NOT NULL,
  `Students_ID` INT(10) NOT NULL,
  `Students_Name` VARCHAR(100) NULL,
  `Students_Phon` VARCHAR(45) NULL,
  `Students_year` VARCHAR(2) NULL,
  PRIMARY KEY (`Students_ID`),
  CONSTRAINT `fk_Students_challenge1`
    FOREIGN KEY (`challenge_University_ID` , `challenge_Year`)
    REFERENCES `ITM_DB`.`challenge` (`University_ID` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Ativity1`
    FOREIGN KEY (`Ativity_Ativity_ID`)
    REFERENCES `ITM_DB`.`Activity` (`Ativity_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,9,59110023," นางสาวกนกอร พึ่งบุญ","0896570188",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,4,59110080," นางสาวกนกวรรณ ขอนทอง","0927481942",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,7,59110155,"นายกฤตภาส ไตรสุวรรณ์","0980898282",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,5,59110460,"นายอภิสิทธิ์ สุวรรณมณี","0976433433",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,6,59110981,"นางสาวกิตติยา แสงขาว","0977892546",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,5,59111120,"นางสาวเกวลิน บ้านควน","0871936595",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,6,59111930,"นายพีรวัส นุเคราะห์ชีพ","0911899850",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,4,59112367,"นายคิม บุญเสริม","0914724278",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,0,59112557,"นายชัยสิทธิ์ คุณาปกรณ์การ","0975642001",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,5,59112615,"นางสาวชุติกาญจน์ ราชฤทธิ์","0944389802",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,2,59112631,"นายณัฐวัฒน์ ลาภามาศ","0917490345",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,8,59113340,"นางสาวณัฐญา บดีรัฐ","0948261903",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,2,59113423,"นายณัฐดนัย จารย์โพธิ์","0896523142",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,9,59113506,"นายณัฐนนท์ เพชรกูล","0943810183",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,3,59113589,"นายณัฐพล บุญสุวรรณ์","0874589216",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,0,59113654,"นางสาวดารียา สังกะหนู","0988756201",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,0,59113969,"นางสาวเดียนา สาและ","0985674803",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,0,59114009,"นางสาวนภสร สมพงษ์","0878777887",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,6,59114314,"นายธนพงษ์ ชุมพล","0622145166",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,4,59114462,"นายธนวัฒน์ อุไรรัตน์","0996542858",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,0,59114819,"นางสาวธิดารัตน์ สุรัตวดี","0812545641",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,5,59115030," นายธีระพงษ์ มะลิพันธ์","0826472910",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,3,59115170,"นางสาวนาตาช่า บินมะดีเย๊าะ","0926489501",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,3,59115600,"นางสาวนาถรภี ศักดี","0935171058",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,3,59115618,"นางสาวนูรมี การี","0847392017",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,3,59115899,"นายธนากรณ์ ศิริผล","0953718105",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,2,59117184,"นายพงศ์ปณต ชูทวด","0948291649",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,2,59118844,"นางสาววรางคณา ลดาวรรษ์","0862518496",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,2,59119438,"นายวณัฐพงค์ ปริตรศิรประภา","0832401026",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,3,59119610,"นายวรวิบูล ไกรแก้ว","0986540112",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,6,59119669,"นางสาววลัยลักษณ์ ลิมปิยประพันธ์","0856281948",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,5,59119784,"นายเศรษฐกิจ สร้างดำรงคุณ","0826374913",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,2,59119891,"นายวายัง ครชาตรี","0977834902",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,4,59120535,"นางสาวศิริกัญญา หัตถการ","0863258742",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,3,59120725,"นางสาวศิวพร เขียวจันทร์","0861846391",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,5,59120881,"นางสาวศุภมิตรา จบถิ่น","0953819190",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,8,59120998,"นายพลรัตน์ รัตนพันธ์","0965810593",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,0,59121368,"นางสาวสิดารัศมิ์ ขาวบาง","0956513241",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,2,59121970,"นางสาวสุภาวดี โพธิ์แป้น","0902678464",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,0,59123380,"นางสาวอัยลดา ชนะกุล","0867262819",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,3,59123570,"นายอารีฟีน กุลดี","0822674161",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,4,59141242,"นางสาวณกรตา เปียทอง","0805542216",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,0,59142026,"นายนคริน บัวหลวง","0952728191",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,0,59142349,"นางสาวเนตรศุภางค์ ชูพยัคฆ์","0954781389",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,0,59142513,"นายปริญญา สุวรรณ","0867183967",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,0,59142802,"นายพงศ์สรรศ์ สัมฤทธิ์","0892736179",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,0,59142901,"นายพัฒนะศักดิ์ พิเศษศิลป์","0875412586",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,0,59143545,"นางสาวรัตนา มาผาสุข","0925371910",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,0,59144097,"นายศิธร เพ็ญพร","0979273618",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,2,59145003,"นายอัสมาวี ลาเตะ","0987261582",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,3,59145219,"นายเอกวิชญ์ จำนงจิต","0885541254",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,4,59147918,"นายณัฐวุฒิ ชูบัวทอง","0965320124",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,5,59190017,"นางสาวกนกพิชญ์ สพานทอง","0851234567",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,2,59190025,"นางสาวกนกวรรณ มณีโลก","0976875795",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,3,59190033,"นางสาวกรกนก ด้วงชู","0852409279",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,5,59190041,"นางสาวจริยมาศ เพชรมีศรี","0844326273",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,6,59190058,"นางสาวจารวี สาริยะสุนทร","0988992323",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,2,59190066,"นางสาวชนัญธิดา สุประวัติตระกูล","0911901099",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,3,59190074,"นางสาวชมพูนุท อ่องอนันตพงศ์","0966843168",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,6,59190082,"นางสาวชลธิชา สกุลชิต","0977865380",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,5,59190090,"นางสาวชัญญา รัตนพฤกษ์ขจร","0844725328",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,6,59190108,"นายณัชพล โชติพัฒน์","0897610123",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,2,59190116,"นายกษิดิศ ไชยสิทธิ์","0976540320",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,3,59190124,"นายภวัต ดาราสูรย์","0955932345",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,6,59190132,"นายศุภณัฐ คงหอม","0900128549",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,5,59190140,"นางสาวณัฐนุช จารุวัฒนสุนทร","0818809900",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,2,59190157,"นายตนัย แก้วจรัส","0834678901",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,3,59190165,"นางสาวตรีชฎา ส่องสุข","0914534353",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,2,59190173,"นายธนกฤต โอลาพฤกษ์","0976498200",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,2,59190181,"นางสาวธนัชญา ปรีชา","0988978799",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,2,59190199,"นายธนาตย์ สิริสงวนศักดิ์","0971622639",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,4,59190207,"นายธเนศ วิเชียร","0811678900",3);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,0,60110053,"นางสาวกนกพิชญ์ หวังแก้ว","0825725237",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,4,60110129,"นางสาวกนกวรรณ เรืองศรี","0927481942",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,0,60110202,"นางสาวกรกนก แก้วคงจันทร์","0896570188",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,2,60110319,"นางสาวกฤติยา ศรีบุญแก้ว","0980898282",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,6,60110350,"นางสาวกษมล สุรภักดี","0977892546",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,6,60110434,"นางสาวกัณฐิกา คงนวล","0871936595",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,3,60110558,"นายกิตติชัย แขสระน้อย","0976433433",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,4,60110590,"นางสาวกิตติยา อ่ำปลอด","0851234567",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,5,60110616,"นางสาวกิติยา พันธ์แทน","0911899850",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,5,60110657,"นายจักรกฤษ มาศภูมิ","0914724278",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,0,60110673,"นางสาวเก็จมณี ทองใบ","0985170491",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,6,60110780,"นางสาวเกษมณี ทุ่งหว้า","0948261903",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,2,60110863,"นายคุนัชญ์ ทองมี","0620735706",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,6,60110947,"นายจักรรินทร์ แพรกทอง","0943810183",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,9,60111069,"นายจิรภัทร ศรีบุญเอียด","0976875795",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,5,60111119,"นายธนดล ศรีสมทรง","0944389802",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,6,60111200,"นายเจตนรินทร์ พูดดี","0622145166",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,5,60111267,"นายวัชรพงษ์ สุขเกษม","0917490345",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,6,60111390,"นางสาวชนัญชิดา หอมทิพย์","0826472910",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,3,60111465,"นายชลธาร แก้วเจริญ","0987047473",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,6,60111804,"นายนิธิศ ขวัญยืน","0988756201",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,6,60112307,"นางสาวตัซลีมา เจ๊ะแว","0985674803",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,6,60112323,"นางสาวตัสนีม ปัญญาผล","0977834902",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,6,60112455,"นายธนกฤต บุญเทียม","0861846391",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,5,60112687,"นางสาวธัญชนก ทองแสน","0953819190",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,5,60112851,"นางสาวธิวาภรณ์ ทองดี","0867262819",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,4,60112869,"นายธีนพัฒน์ รัตนวงศ์","0935754721",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,5,60112893,"นายธีรพงศ์ หนูสุข","0952728191",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,0,60113008,"นายนฤเบศ รีวรรณ","0965605539",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,5,60113024,"นายกรินทร์ เกตุพงษ์","0954781389",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,5,60113354,"นายกัมพล เงินส่ง","0867183967",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,2,60113479,"นายบุรินทร์ พันธุ์ชาติ","0937131682",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,3,60113834,"นางสาวปัญญพัฒน์ เจือบุญ","0895962839",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,4,60113958,"นายปิยะ บุญมี","0892736179",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,6,60114014,"นางสาวปิยะวรรณ หงษ์ชู","0852409279",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,4,60114105,"นายพงศธร รักทอง","0956207196",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,4,60114238,"นายพฤทธิ์ ดำศรี","0925371910",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,4,60114329,"นางสาวพัชราภรณ์ เพ็ชรรัตน์","0979273618",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,4,60114444," นายพิชาภพ พรัดเมือง","0982736271",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,0,60118296,"นายศิริศักดิ์ ใหม่สุดใจ","0962578132",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,4,60119260,"นายอภิรักษ์ ศรีน้อย","0844326273",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,5,60120276,"นายกิตติศักดิ์ เยาว์ดำ","0988992323",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,2,60120474,"นายธนภัทร เทพจันทร์","0911901099",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,3,60140019,"นายอัดดีน ตุลยาพงศ์","0966843168",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,2,60140365,"นายกิตติพงษ์ ทูรย์ภานุประพันธ์","",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,3,60140852,"นางสาวจุติมาศ มาลัย","0610362751",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,5,60140928,"นางสาวชนากานต์ ไพรบึง","0977865380",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,6,60140985,"นางสาวชยานันท์ ศรียาบ","0844725328",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,5,60141124,"นางสาวซูฮัยระห์ สมูนิง","0897610123",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,4,60141207,"นางสาวฐิติกร เหมือนเสน","0976540320",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,5,60141231,"นายศักนรินทร์ โอทองคำ","0955932345",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,6,60141280,"นายพงศกร อ่อนชะเวียง","0818809900",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,8,60141785,"นางสาวกชกร ฟักทองผล","0825725237",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,0,60141900,"นางสาวธัญวรัตน์ จินดา","0987252639",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,4,60144235,"นางสาวศิริรัตน์ วิชิตแย้ม","0872772564",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,2,60144730,"นายสุทธิพงษ์ จินตาแก้ว","0913152524",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,3,60144961,"นางสาวเสาวรัตน์ ชวนดี","0950132150",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,5,60146313,"นายชัชวาล สุคนธปฏิภาค","0968099926",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,6,60191053,"นางสาวอะวาฏิฟ ยูโซ๊ะ","0622145166",2);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,3,61100285,"นายกรินทร์ เกตุพงษ์","0851234567",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,4,61100301,"นายกฤตพณ ประสมแก้ว","0825725237",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,2,61100640," นายกัมพล เงินส่ง","0976875795",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,4,61100699,"นางสาวกานติมา หมัดเต๊ะ","0896570188",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,9,61100962,"นางสาวเกศิณี คำสุวรรณ","0927481942",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,4,61101184,"นายจริณทร์พร ชูทอง","0852409279",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,4,61101192,"นางสาวจริยาวดี เนียมนาค","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,7,61101234,"นายจักรกฤษ มาศภูมิ","0844326273",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,5,61101242,"นายจักรพงษ์ กระต่ายทอง","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,5,61101259,"นายจักรพันธ์ ลับแสง","0977892546",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,8,61101291,"นางสาวจันทกานติ์ ฉิมเกื้อ","0988992323",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,6,61101374,"นางสาวจิณห์วรา แสงผดุง","0871936595",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,9,61101481,"นายจิรพนธ์ ใจยะกว้าง","0911901099",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,2,61101507,"นางสาวจิรัชญา ญาณะวุฒิโท","0980898282",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,6,61101655,"นางสาวจุฑาภรณ์ พุ่มมณี","0971719806",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,5,61101747,"นางสาวจูวัยนีย์ ยีสา","0948261903",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,6,61101812," นายเจษฎา แสงสุวรรณ","0966843168",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,2,61101820,"นายเจษฎากรณ์ ตีระกนก","0976433433",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,5,61101929,"นางสาวชนกานต์ บุญสุด","0977865380",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,2,61102158,"นางสาวชัญญานุช แซ่เจีย","0844725328",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,3,61102166,"นางสาวชัญญานุช ปานแก้ว","0844725328",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,2,61102182," นายชัยรัตน์ อินรินทร์","0976540320",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,2,61102299,"นายโชติวิชช์ วรเดช","0887826793",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,9,61102323,"นายซีน ละเอียด","0943810183",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,3,61102695,"นายณัฐชานนท์ ทองน้อย","0955932345",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,2,61102786,"นางสาวณัฐนรี เทศวงษ์","0911899850",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,8,61102943,"นายณัฐวุฒิ ศรีบุญ","0622145166",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,2,61103115,"นางสาวดุสิตตา ปิดเมือง","0900128549",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,4,61103271,"นางสาวทิพมาดา ทองเรือง","0818809900",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,2,61103313,"นางสาวทิษฏยา หนูทอง","0914724278",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,5,61103388,"นายธนดล ศรีสมทรง","0834678901",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,6,61103610,"นางสาวธัญชนก ส่งแสง","0914534353",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,3,61103776,"นายธิติพงศ์ ปุรินสุวรรณ","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,2,61103826,"นายธีรภัทร คงกลั้ง","0944389802",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,5,61103867,"นายธีระพงษ์ สวนแก้ว","0976498200",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,9,61103883," นางสาวนงนภัส บุญโยดม","0988978799",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,6,61103917,"นายนนธวัฒชัย เมืองประทับ","0971622639",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,3,61104105,"นางสาวนฤมล จันทร์ไพฑูรย์","0917490345",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,5,61104139,"นายนลธวัช แก้วจีน","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,3,61104147,"นางสาวนวพรรษ ตะกี่","0988756201",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,5,61104378,"นางสาวน้ำทิพย์ ยอดโสภณ","0826472910",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (102,1,7,61104741,"นายบริพัตร ด้วงชุม","0811678900",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,6,61105193,"นางสาวประณิตา กะตากูล","0977834902",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,4,61105482,"นายปานเทพ ศรีสมโภชน์","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,5,61105573,"นางสาวปิยฉัตร หมื่นแก้ว","0861846391",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,3,61105599,"นางสาวปิยธิดา พูลพิพัฒน์","0985674803",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,6,61105631,"นางสาวปิยมินทร์ ใจมา","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,3,61105789,"นายพงศกร จิตรแก้ว","0878777887",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,2,61105888,"นายพนมกร มหาสวัสดิ์","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,8,61106217,"นายพันธิน เธียรสุคนธ์","0953819190",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,3,61106860,"นายภานุพงศ์ เชาวลิต","0926489501",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,9,61106902,"นางสาวภูมิชีวา กลิ่นทอง","0867262819",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,3,61107058,"นางสาวมัณฑิตา แก้วสุด","0935171058",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,0,61107223,"นางสาวเมธิณีย์ แก่นทอง","0847392017",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,0,61107330,"นายรพีภัทร์ สมปรีดา","0953718105",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,6,61107686,"นายวรเมธ ขวัญนิมิตร","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,0,61108130,"นางสาววิลาวรรณ จริงเจียว","0948291649",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,0,61108148,"นางสาววิลาวัลย์ เพ็งสกุล","0862518496",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,8,61108262,"นางสาวศรินญา คงเส้ง","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,0,61108601,"นายศุภกิตติ์ สาธุ","0856281948",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,9,61108718,"นางสาวสจีหัสสา อินทรวิมล","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,6,61108874,"นางสาวสหัสมณี สุวรรณชาตรี","0952728191",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,0,61109294,"นางสาวสุธิตรา สมปรีดา","0826374913",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,5,61109443," นางสาวสุพิชชา เพ็ชรประสมกูล","0954781389",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (101,1,9,61109468,"นางสาวสุพิชชา รัตนชู","0965810593",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,4,61109641,"นางสาวสุวารี เส็นบัตร","0867183967",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,2,61110474,"นายอัสรอฟ ลาเต๊ะ","0892736179",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,3,61110490,"นายอาทิตย์ สายแก้ว","0925371910",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,4,61110888,"นางสาวกวินทิพย์ ชูชัยทยากุล","0979273618",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,5,61111191,"นางสาวจิราวรรณ ช่วยแก้ว","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,4,61111415,"นางสาวชุติมา อนันตกูล","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,3,61113239,"นายวิทวัส ช่วยพนัง","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,6,61113403,"นายศิวกร หนักแน่น","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,4,61113619,"นายสิทธินนท์ เดิมหลิ่ม","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,0,61113858,"นายสุวิจักขณ์ พิศสุพรรณ","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,2,61114005,"นายอภิยุต เชื้อมณี","0982736271",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,3,61114864,"นางสาวญาณิศา อินพฤกษา","0948372511",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (201,1,5,61114914,"นางสาวนูรีย์ สะดี","0972936351",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,0,61115184,"นายก่อกฤษฎิ์ อินทิศ","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,0,61115267,"นางสาวชนิกานต์ พจมานพงศ์","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,3,61116141,"นายณธกร จิระอรรคพงษ์","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,2,61118717,"นายรัตธนาตย์ รัตนพันธุ์","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,5,61120531,"นายชุมพร แก้วพิทักษ์","0952640750",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,6,61122685,"นางสาวสัณห์สินี รักเนียม","",1);
INSERT INTO `itm_db`.`students` (`challenge_University_ID`, `challenge_Year`, `Ativity_Ativity_ID`, `Students_ID`, `Students_Name`, `Students_Phon`, `Students_year`) VALUES (301,1,8,591199410,"นางสาววิชุตา หมาดอะดำ","0987135415",3);

-- -----------------------------------------------------
-- Table `ITM_DB`.`Teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITM_DB`.`Teachers` ;

CREATE TABLE IF NOT EXISTS `ITM_DB`.`Teachers` (
  `Teachers_ID` INT NOT NULL,
  `Teachers_Name` VARCHAR(100) NULL,
  `Teachers_Phon` VARCHAR(45) NULL,
  `challenge_University_ID` INT NOT NULL,
  `challenge_Year` INT NOT NULL,
  PRIMARY KEY (`Teachers_ID`),
  CONSTRAINT `fk_Teachers_challenge1`
    FOREIGN KEY (`challenge_University_ID` , `challenge_Year`)
    REFERENCES `ITM_DB`.`challenge` (`University_ID` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITM_DB`.`Responsibility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITM_DB`.`Responsibility` ;

CREATE TABLE IF NOT EXISTS `ITM_DB`.`Responsibility` (
  `Teachers_Teachers_ID` INT NOT NULL,
  `Ativity_Ativity_ID` INT NOT NULL,
  `Responsibility_status` VARCHAR(20) NULL,
  PRIMARY KEY (`Teachers_Teachers_ID`, `Ativity_Ativity_ID`),
  CONSTRAINT `fk_Teachers_has_Ativity_Teachers1`
    FOREIGN KEY (`Teachers_Teachers_ID`)
    REFERENCES `ITM_DB`.`Teachers` (`Teachers_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teachers_has_Ativity_Ativity1`
    FOREIGN KEY (`Ativity_Ativity_ID`)
    REFERENCES `ITM_DB`.`Activity` (`Ativity_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITM_DB`.`joinAtivity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITM_DB`.`joinAtivity` ;

CREATE TABLE IF NOT EXISTS `ITM_DB`.`joinAtivity` (
  `Students_ID` INT(10) NOT NULL,
  `Ativity_ID` INT NOT NULL,
  `joinAtivity_Results` VARCHAR(10) NULL,
  PRIMARY KEY (`Students_ID`, `Ativity_ID`),
  CONSTRAINT `fk_Students_has_Ativity_Students1`
    FOREIGN KEY (`Students_ID`)
    REFERENCES `ITM_DB`.`Students` (`Students_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_has_Ativity_Ativity1`
    FOREIGN KEY (`Ativity_ID`)
    REFERENCES `ITM_DB`.`Activity` (`Ativity_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
